words = [
    "bundler",
    "cadd",
    "clsx",
    "direnv",
    "dlx",
    "fontsource",
    "lucide",
    "pocketbase",
    "podman",
    "shadcn",
    "sveltejs",
    "vite",
    "wget",
    "wsl",
]
