services:
  ping_db:
    image: docker.io/library/postgres:17-alpine
    container_name: ping_db
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${HOME}/.var/postgresql/ping_db/data:/var/lib/postgresql/data
